MvcProjeKampi/Controllers/ContactController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRıles;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntitiyLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        ContactManager cm = new ContactManager(new EfContactDal());
        MessageManager mm = new MessageManager(new EfMessageDal());
        DraftManager dm = new DraftManager(new EfDraftDal());
        ContactValidator cv = new ContactValidator();
        public ActionResult Index()
        {
            var contactvalues = cm.GetList();
            return View(contactvalues);
        }
        public ActionResult GetContactDetails(int id)
        {
            var contactvalues = cm.GetByID(id);
            return View(contactvalues);
        }
        public PartialViewResult MessageListMenu()
        {
            string p = (string)Session["WriterMail"];
            var draftCount = dm.GetList().Count();
            var contactCount = mm.GetListInbox(p).Count();
            var contactCount2 = mm.GetListSendbox(p).Count();
            var contactCount3 = cm.GetList().Count();
            var contactFalseCount = cm.GetList().Where(x => x.ContactReadStatus == false).Count();
            var contactTrueCount = cm.GetList().Where(x => x.ContactReadStatus == true).Count();
            var messageFalseCount = mm.GetListInbox(p).Where(x => x.MessageReadStatus == false).Count();
            var messageTrueCount = mm.GetListInbox(p).Where(x => x.MessageReadStatus == true).Count();
            ViewBag.draft = draftCount;
            ViewBag.adminInbox = contactCount;
            ViewBag.adminSendbox = contactCount2;
            ViewBag.Inbox = contactCount3;
            ViewBag.CFalseCount = contactFalseCount;
            ViewBag.CTrueCount = contactTrueCount;
            ViewBag.MFalseCount = messageFalseCount;
            ViewBag.MTrueCount = messageTrueCount;
            return PartialView();
        }
        public ActionResult UpdateContractReadStatus(int id)
        {
            var HeadingValue = cm.GetByID(id);
            HeadingValue.ContactReadStatus = true;
            cm.ContactUpdate(HeadingValue);
            return RedirectToAction("Index");
        }
    }
}

MvcProjeKampi/Controllers/DraftController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class DraftController : Controller
    {
        // GET: Draft
        DraftManager dm = new DraftManager(new EfDraftDal());
        public ActionResult Index()
        {
            return View(dm.GetList());
        }
        [HttpPost]
        public ActionResult AddDraft(Draft p)
        {
            
            dm.DraftAddBL(p);
            return RedirectToAction("Index");
            
        }
        public ActionResult GetDraftMessageDetails(int id)
        {
            var values = dm.GetByID(id);
            return View(values);
        }
    }
}

MvcProjeKampi/Controllers/MessageController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRıles;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class MessageController : Controller
    {
        // GET: Message
        MessageManager mm = new MessageManager(new EfMessageDal());
        MessageValidator validationRules = new MessageValidator();
        [Authorize]
        public ActionResult Inbox(string p)
        {
            var messageList = mm.GetListInbox(p);
            return View(messageList);
        }
        public ActionResult Sendbox(string p)
        {
            var messageList = mm.GetListSendbox(p);
            return View(messageList);
        }
        public ActionResult GetInboxMessageDetails(int id)
        {
            var values = mm.GetByID(id);
            return View(values);
        }
        public ActionResult GetSendboxMessageDetails(int id)
        {
            var values = mm.GetByID(id);
            return View(values);
        }
        [HttpGet]
        public ActionResult NewMessage()
        {
            return View();
        }
        [HttpPost]
        public ActionResult NewMessage(Message p)
        {
            //var messageList = mm.GetListSendbox();
            //return View(messageList);
            ValidationResult result = validationRules.Validate(p);
            if (result.IsValid)
            {
                p.SenderMail = "admin@gmail.com";
                p.MessageDate = DateTime.Parse(DateTime.Now.ToShortDateString());
                mm.MessageAddBL(p);
                return RedirectToAction("Sendbox");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
            
        }
        public ActionResult UpdateMessageReadStatus(int id)
        {
            var HeadingValue = mm.GetByID(id);
            HeadingValue.MessageReadStatus = true;
            mm.MessageUpdate(HeadingValue);
            return RedirectToAction("Inbox");
        }
    }
}

MvcProjeKampi/Views/Message/GetInboxMessageDetails.cshtml
@model EntityLayer.Concrete.Message
@{
    ViewBag.Title = "GetInboxMessageDetails";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Gelen Mesaj Detayları</h1>
                </div>
                
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                 @Html.Action("MessageListMenu", "Contact")
                <!-- /.col -->
                <div class="col-md-9">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h3 class="card-title">Mesajı Oku</h3>
                            <div class="card-tools">
                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Previous"><i class="fas fa-chevron-left"></i></a>
                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Next"><i class="fas fa-chevron-right"></i></a>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            <div class="mailbox-read-info">
                                <h5>Konu: @Html.DisplayFor(x => x.Subject)</h5>
                                <h6>
                                    Mail: @Html.DisplayFor(x => x.SenderMail)
                                    <span class="mailbox-read-time float-right">
                                    @DateTime.Parse(Html.DisplayFor(x => x.MessageDate).ToString()).ToShortDateString()</span>
                                </h6>
                            </div>
                            <!-- /.mailbox-read-info -->
                            <!-- /.mailbox-controls -->
                            <div class="mailbox-read-message">
                                @{ HtmlString messageContext = new HtmlString(@Model.MessageContent);}
                                <p>@messageContext</p>
                            </div>
                            <!-- /.mailbox-read-message -->
                        </div>
                        <!-- /.card-footer -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
    </section>
</body>
</html>

MvcProjeKampi/Views/Message/GetSendboxMessageDetails.cshtml
@model EntityLayer.Concrete.Message
@{
    ViewBag.Title = "GetSendboxMessageDetails";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Gelen Mesaj Detayları</h1>
                </div>

            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                @Html.Action("MessageListMenu", "Contact")
                <!-- /.col -->
                <div class="col-md-9">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h3 class="card-title">Mesajı Oku</h3>
                            <div class="card-tools">
                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Previous"><i class="fas fa-chevron-left"></i></a>
                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Next"><i class="fas fa-chevron-right"></i></a>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            <div class="mailbox-read-info">
                                <h5>Konu: @Html.DisplayFor(x => x.Subject)</h5>
                                <h6>
                                    Alıcı: @Html.DisplayFor(x => x.RecieverMail)
                                    <span class="mailbox-read-time float-right">
                                        @DateTime.Parse(Html.DisplayFor(x => x.MessageDate).ToString()).ToShortDateString()
                                    </span>
                                </h6>
                            </div>
                            <!-- /.mailbox-read-info -->
                            <!-- /.mailbox-controls -->
                            <div class="mailbox-read-message">
                                @{ HtmlString messageContext = new HtmlString(@Model.MessageContent);}
                                <p>@messageContext</p>
                            </div>
                            <!-- /.mailbox-read-message -->
                        </div>
                        <!-- /.card-footer -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
    </section>
</body>
</html>

MvcProjeKampi/Views/Message/Inbox.cshtml
@using EntityLayer.Concrete
@model List<Message>
@{
    ViewBag.Title = "Inbox";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<html>

<body class="hold-transition sidebar-mini">

    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Mesaj Sayfası</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            @Html.Action("MessageListMenu", "Contact")
            <!-- /.col -->
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Gelen Mesajlar</h3>
                        <div class="card-tools">
                            <div class="input-group input-group-sm">
                                <input type="text" class="form-control" placeholder="Mail Kutusunda Ara">
                                <div class="input-group-append">
                                    <div class="btn btn-primary">
                                        <i class="fas fa-search"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                <i class="far fa-square"></i>
                            </button>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                            </div>
                            <!-- /.btn-group -->
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                        <div class="table-responsive mailbox-messages">
                            <table class="table table-hover table-striped">
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                    <tr>
                                        <td>
                                            <div class="icheck-primary">
                                                <input type="checkbox" value="" id="check1">
                                                <label for="check1"></label>
                                            </div>
                                        </td>

                                        <td class="mailbox-star"><a href="/Message/GetInboxMessageDetails/@item.MessageID"><i class="fas fa-star text-warning"></i></a></td>
                                        <td class="mailbox-name"><a href="/Message/GetInboxMessageDetails/@item.MessageID">@item.SenderMail</a></td>
                                        <td class="mailbox-subject">
                                            @{ HtmlString messageContext = new HtmlString(@item.MessageContent);}
                                            <b>@item.Subject</b> - @messageContext
                                        </td>
                                        <td class="mailbox-attachment"></td>
                                        <td>
                                            @if (item.MessageReadStatus == false)
                                            {
                                                <a class="btn btn-danger" href="/Message/UpdateMessageReadStatus/@item.MessageID">
                                                    <i class="fas fa-redo"> Okundu Olarak İşaretle</i>
                                                </a>
                                            }
                                            else
                                            {<a class="btn btn-success btn-sm" href="#"><i class="fas fa-spell-check"> Okundu</i></a>}
                                        </td>
                                        <td class="mailbox-date">@(((DateTime)item.MessageDate).ToString("dd-MMM-yyyyy")) </td>
                                    </tr>
                                    }
                                </tbody>
                            </table>
                            <!-- /.table -->
                        </div>
                        <!-- /.mail-box-messages -->
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                <i class="far fa-square"></i>
                            </button>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                            </div>
                            <!-- /.btn-group -->
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>

</body>
</html>

MvcProjeKampi/Views/Message/NewMessage.cshtml
@model EntityLayer.Concrete.Message
@{
    ViewBag.Title = "NewMessage";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Compose Message</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <!-- Theme style -->
    <!-- summernote -->
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.css">

    <script src="~/AdminLTE-3.0.4/plugins/summernote/summernote.min.js"></script>
</head>
<body class="hold-transition sidebar-mini">

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Yeni Mesaj Sayfası</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                @Html.Action("MessageListMenu", "Contact")
                <!-- /.col -->
                <div class="col-md-9">
                    @using (Html.BeginForm(FormMethod.Post))
                    {
                        <div class="card card-primary card-outline">
                            <div class="card-header">
                                <h3 class="card-title">Yeni Mesaj Oluştur</h3>
                            </div>
                            <!-- /.card-header -->

                            <div class="card-body">
                                <div class="form-group">
                                    @Html.TextBoxFor(x => x.RecieverMail, new { @class = "form-control", @placeholder = "Alıcı:" })
                                    @Html.ValidationMessageFor(x => x.RecieverMail)
                                </div>
                                <div class="form-group">
                                    @Html.TextBoxFor(x => x.Subject, new { @class = "form-control", @placeholder = "Konu:" })
                                    @Html.ValidationMessageFor(x => x.Subject)
                                </div>
                                <div class="form-group">
                                    <textarea id="compose-textarea" name="MessageContent" class="form-control" style="height:300px"></textarea>
                                </div>
                                <div class="form-group">
                                    <div class="btn btn-default btn-file">
                                        <i class="fas fa-paperclip"></i> Dosya Ekle
                                        <input type="file" name="attachment">
                                    </div>
                                    <p class="help-block">Max. 32MB</p>
                                </div>
                            </div>

                            <div class="card-footer">
                                <div class="float-right">
                                    <button type="submit" class="btn btn-default"formaction=@Url.Action("AddDraft", "Draft")><i class="fas fa-pencil-alt">Taslaklara Kaydet</i></button>
                                    <button type="submit" class="btn btn-primary" formaction=@Url.Action("NewMessage", "Message")><i class="far fa-envelope"></i> Gönder</button>
                                </div>
                                <button type="reset" class="btn btn-default"><i class="fas fa-times"></i> İptal Et</button>
                            </div>
                            <!-- /.card-footer -->
                        </div>
                    }
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
    <!-- /.content-wrapper -->
    <!-- Control Sidebar -->
    <!-- /.control-sidebar -->
    <!-- jQuery -->
    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>
    <!-- Summernote -->
    <script src="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- ./wrapper -->
    <!-- Page Script-->
    <script>
        $(function () {
            //Add text editor
            $('#compose-textarea').summernote()
        })</script>

</body>
</html>

MvcProjeKampi/Views/Message/Sendbox.cshtml
@using EntityLayer.Concrete
@model List<Message>
@{
    ViewBag.Title = "Sendbox";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<html>

<body class="hold-transition sidebar-mini">

    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Mesaj Sayfası</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            @Html.Action("MessageListMenu", "Contact")
            <!-- /.col -->
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Gönderilen Mesajlar</h3>
                        <div class="card-tools">
                            <div class="input-group input-group-sm">
                                <input type="text" class="form-control" placeholder="Mail Kutusunda Ara">
                                <div class="input-group-append">
                                    <div class="btn btn-primary">
                                        <i class="fas fa-search"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                <i class="far fa-square"></i>
                            </button>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                            </div>
                            <!-- /.btn-group -->
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                        <div class="table-responsive mailbox-messages">
                            <table class="table table-hover table-striped">
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                <div class="icheck-primary">
                                                    <input type="checkbox" value="" id="check1">
                                                    <label for="check1"></label>
                                                </div>
                                            </td>
                                            <td class="mailbox-star"><a href="/Message/GetSendboxMessageDetails/@item.MessageID"><i class="fas fa-star text-warning"></i></a></td>
                                            <td class="mailbox-name"><a href="/Message/GetSendboxMessageDetails/@item.MessageID">@item.RecieverMail</a></td>
                                            <td class="mailbox-subject">
                                                @{ HtmlString messageContext = new HtmlString(@item.MessageContent);}
                                                <b>@item.Subject</b> - @messageContext
                                            </td>
                                            <td class="mailbox-attachment"></td>
                                            <td class="mailbox-date"> @(((DateTime)item.MessageDate).ToString("dd-MMM-yyyyy")) </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                            <!-- /.table -->
                        </div>
                        <!-- /.mail-box-messages -->
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                <i class="far fa-square"></i>
                            </button>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                            </div>
                            <!-- /.btn-group -->
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>

</body>
</html>